environment:
    #
    # This variables defines initial stage3 image from which the Gentoo docker
    # image will be built in reproducable manner:
    GENTOO_BOOTSTRAP: "multiarch/alpine:x86-v3.7"
    # ^^^ NOTE: may not be consumed depending on docker version
    GENTOO_STAGE3_ARCH: "amd64"
    GENTOO_STAGE3_MICROARCH: ""
    GENTOO_STAGE3_SUFFIX: ""
    GENTOO_STAGE3_MIRROR: "https://ftp-osl.osuosl.org/pub/gentoo/releases/amd64/autobuilds"
    GENTOO_STAGE3_TAG: "20180311T214502Z"  # TODO: understand T...Z part it and rename var
    # Portage snapshot ID to provide reproducable builds:
    PORTAGES_SNAPSHOT_ID: "20180318"
    #
    # This variable controls system-wide configuration of the generated OS
    # image. Currently only [dev|prod] variants are supported.
    SYS_PROFILE: dev

